### PR TITLE
QuestEDIT | Thumbnail | ver_001 Pass for Collaboration

### PR DESCRIPTION
**Pull request by TreeStrepek**
@Maia please look at model pieces.  

Here’s a targeted list as you requested: 

1-Repair Logout function
2-Repair Image uploads 
     *Quest.icon_url
     *User.avatar_url
3-missionBuilder isn’t saving.  Available fields in the dbase are on the form & wired up. but a query to true dbase shows 0 records post save.
4-mission-quest link
5-I restored EDIT for Quests (view.html)  Unfortunately It is not loading our data.  I think the controller needs attention?  Can you look at that?
6-(quest + mission )thumbnails floating
7- Question:  Should I be able to populate these table.field values from QuestBuilder?
     *questNew.users.name
     *quest_tags.name
     *questions.description
     *multiple_choices.answer

### CODE REVIEW

**Comment by andymcguinness** [comment]
Be careful with at symbols, you tagged a wildly random user with that. @andymcguinness if you want to tag me. But thank you for the list -- I'll keep plugging away with that.

**Comment by maia** [comment]
I like the changes! ;)

**Comment by andymcguinness** [comment]
:+1:

**Comment by TreeStrepek** [comment]
i hear ya.  did that person reach out to you?  TheresaStrepekOracle Middleware DeveloperMobile | Fusion | AngularJS 


-------- Original Message --------
Subject: Re: [Planet-Lab] QuestEDIT | Thumbnail | ver_001 Pass for
Collaboration (#6)

**Pull request merged**
